### YamlMime:Role 
title: 管理者 
metadata: 
  title: 管理者 
  description: 管理者は、計算、ストレージ、ネットワーク、セキュリティに関連する主要サービスを含めて、Microsoft Azure Solution の実行、監視、保守を行います。
uid: role.administrator 
summary: | 
  管理者は、計算、ストレージ、ネットワーク、セキュリティに関連する主要サービスを含めて、Microsoft Azure Solution の実行、監視、保守を行います。
subTitle: 管理者は、 Microsoft のソリューションを実行、監視、保守を行います。
certificationPaths: 
- title: Azure Administrator
  linkedInKeywords: Azure Administrator
  uid: certification-path.azure-administrator 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-administrator
    levels:
    - intermediate
  - uid: certification.azure-devops
    levels:
    - advanced      
- title: Microsoft 365 Certified Messaging Administrator Associate
  linkedInKeywords: Microsoft 365 Certified Messaging Administrator Associate
  uid: certification.m365-messaging-administrator
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-messaging-administrator
    levels:
    - intermediate  
  - uid: certification.m365-enterprise-administrator
    levels:
    - advanced
- title: Microsoft 365 Certified Modern Desktop Administrator Associate
  linkedInKeywords: Microsoft 365 Certified Modern Desktop Administrator Associate
  uid: certification.modern-desktop
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.modern-desktop
    levels:
    - intermediate  
  - uid: certification.m365-enterprise-administrator
    levels:
    - advanced
- title: Microsoft 365 Certified Security Administrator Associate
  linkedInKeywords: Microsoft 365 Certified Security Administrator Associate
  uid: certification.m365-security-administrator
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-security-administrator
    levels:
    - intermediate  
  - uid: certification.m365-enterprise-administrator
    levels:
    - advanced
- title: Microsoft 365 Certified Teamwork Administrator Associate
  linkedInKeywords: Microsoft 365 Certified Teamwork Administrator Associate
  uid: certification.m365-teamwork-administrator
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-teamwork-administrator
    levels:
    - intermediate  
  - uid: certification.m365-enterprise-administrator
    levels:
    - advanced
- title: Microsoft Teams Administrator
  linkedInKeywords: Microsoft Teams Administrator
  uid: certification.m365-teams-administrator-associate
  prerequisites: 
  - uid: certification.microsoft-365-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.m365-teams-administrator-associate
    levels:
    - intermediate
certifications:
- uid: certification.azure-administrator
  requiredExams:
  - uid: exam.az-103 
- uid: certification.azure-devops
  requiredExams:
  - uid: exam.az-400
- uid: certification.m365-messaging-administrator
  requiredExams:
  - uid: exam.ms-200
  - uid: exam.ms-201
- uid: certification.modern-desktop
  requiredExams:
  - uid: exam.md-100
  - uid: exam.md-101
- uid: certification.m365-security-administrator
  requiredExams:
  - uid: exam.ms-500
- uid: certification.m365-teamwork-administrator
  requiredExams:
  - uid: exam.ms-300
  - uid: exam.ms-301
- uid: certification.m365-enterprise-administrator
  requiredExams:
  - uid: exam.ms-100
  - uid: exam.ms-101
- uid: certification.m365-teams-administrator-associate
  requiredExams:
  - uid: exam.ms-700
resources:
- title: Microsoft トレーニングおよび認定資格のガイド
  description: 簡潔なトレーニングおよび認定資格ガイドですべての認定資格をご確認ください。
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: トレーニングおよび認定資格のポスター
  description: このトレーニングおよび認定資格のポスターで、成功への道を選択してください。
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: 資格のサポート
  href: ../help.md
  description: Microsoft Certificate サポートフォーラムで助けてもらう。フォーラムモデレーターが 1 営業日（月曜日から金曜日）以内に返信します。
