### YamlMime:Role 
title: DevOps エンジニア
metadata: 
  title: DevOps エンジニア
  description: DevOps エンジニアは、エンドユーザーのニーズおよびビジネスの目的を満たす価値のある製品・サービスを継続的に供給するために、人とプロセスとテクノロジーを結合させます。
uid: role.devops-engineer 
summary: | 
  DevOps エンジニアは、エンドユーザーのニーズおよびビジネスの目的を満たす価値のある製品・サービスを継続的に供給するために、人とプロセスとテクノロジーを結合させます。
subTitle: DevOps エンジニアは、エンドユーザーのニーズおよびビジネスの目的を満たす価値のある製品・サービスを継続的に供給するために、人とプロセスとテクノロジーを結合させます。
certificationPaths: 
- title: Azure DevOps Engineer
  linkedInKeywords: Azure DevOps Engineer
  uid: certification-path.devops 
  prerequisites: 
  - uid: certification.azure-fundamentals
    isOptional: true
    levels:
    - beginner 
  - uid: certification.azure-devops
    levels:
    - advanced    
certifications:
- uid: certification.azure-devops
  requiredExams:
  - uid: exam.az-400
resources:
- title: Microsoft トレーニングおよび認定資格のガイド
  description: 簡潔なトレーニングおよび認定資格ガイドですべての認定資格をご確認ください。
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: トレーニングおよび認定資格のポスター
  description: このトレーニングおよび認定資格のポスターで、成功への道を選択してください。
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: 資格のサポート
  href: ../help.md
  description: Microsoft Certificate サポートフォーラムで助けてもらう。フォーラムモデレーターが 1 営業日（月曜日から金曜日）以内に返信します。
