### YamlMime:Certification
title: 'MCSE: Business Applications'
metadata:
  title: 'MCSE: Business Applications'
  description: 'MCSE: Business Applications'
uid: certification.mcse-business-applications
iconUrl: /media/learn/certification/badges/mcse-badge.svg
summary: |-
  <div>
  <div style='color&#58; red;'><strong>コロナウイルス (COVID-19) の状況に対応して、Microsoft はトレーニングおよび認定プログラムにいくつかの一時的な変更を実施しています。<a href='https://www.microsoft.com/en-us/learning/community-blog-post.aspx?BlogId=8&amp;Id=375289'>詳細について学びます</a>。</strong><br/><br/></div>
  <div><strong>この認定資格は 2021 年 1 月 31 日に廃止されます。その日以降、この認定資格を取得することはできなくなります。終了日前に取得した認定資格は、今後も <a href='https://www.microsoft.com/learning/dashboard.aspx'>認定資格ダッシュボード</a>におけるトランスクリプトに表示されます。<a href='/learn/certifications/retired-certifications'>停止されたすべての認定資格を閲覧する</a>こともできます。</strong><br/><br/></div>
  </div>

  この資格によって、あなたが Microsoft Dynamics 365テクノロジーを使っての仕事をする事が出来ることを証明できます。Microsoft Dynamics 365の基礎から始まって、さらに追加で他のビジネス特定エリアの技能を証明できます。

  MCSE&#58; Business Applications の認定資格を取得するためには、以下の試験のいずれかに合格する必要があります。
  - [MB2-716&#58; Microsoft Dynamics 365 Customization and Configuration](/learn/certifications/exams/mb2-716)
  - [MB2-718&#58; Microsoft Dynamics 365 for Customer Service](/learn/certifications/exams/mb2-718)
  - [MB2-719&#58; Microsoft Dynamics 365 for Marketing](/learn/certifications/exams/mb2-719)
  - [MB6-895&#58; Financial Management in Microsoft Dynamics 365 for Finance and Operations](/learn/certifications/exams/mb6-895)
  - [MB6-896&#58; Distribution and Trade in Microsoft Dynamics 365 for Finance and Operations](/learn/certifications/exams/mb6-896)
  - [MB6-897&#58; Microsoft Dynamics 365 for Retail](/learn/certifications/exams/mb6-897)
  - [MB6-898&#58; Microsoft Dynamics 365 for Talent](/learn/certifications/exams/mb6-898)
subTitle: この資格によって、あなたが Microsoft Dynamics 365テクノロジーを使っての仕事をする事が出来ることを証明できます。Microsoft Dynamics 365の基礎から始まって、さらに追加で他のビジネス特定エリアの技能を証明できます。
levels:
- beginner
skills:
- none
roles:
- business-analyst
type: mcse
products:
- dynamics
exams:
- uid: exam.mb-2-716
- uid: exam.mb-6-897
- uid: exam.mb-6-898
resources:
- title: トレーニングおよび認定資格ガイド
  description: 簡潔なトレーニングおよび認定ガイドですべての認定を確認してください。
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RWtQJJ
- title: 認定ポスター
  description: 基礎、ロールベースおよび専門認定の概要をご覧ください。
  href: https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2PjDI
- title: Exam Replay
  description: 成功の可能性を一気に高めるために2つの素晴らしいオファーを見てみましょう。
  href: deals.md
- title: 資格のサポート
  description: Microsoft Certification サポートフォーラムで助けてもらう。フォーラムのモデレーターが、月曜日から金曜日までの 1 営業日以内に返信します。
  href: help.md
- title: 認定資格ダッシュボード
  description: スケジュールされた予定、認定証、および成績証明書をご確認および管理してください。
  href: https://www.microsoft.com/learning/dashboard.aspx

